- name: Configurar clientes DHCP
  hosts: dhcp_clients
  become: yes
  tasks:

    - name: Instalar cliente DHCP
      apt:
        name: isc-dhcp-client
        state: present
        update_cache: yes

    - name: Configurar interfaz eth1 como cliente DHCP
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto eth1
          iface eth1 inet dhcp

    - name: Reiniciar la interfaz de red para aplicar DHCP
      shell: |
        ifdown eth1 || true
        ifup eth1

    - name: Obtener configuración IP
      command: ip -4 a show eth1
      register: ip_config

    - debug:
        var: ip_config.stdout_lines
